// Generated by scripts/gen_partition_header.py from partitions.json; do not edit by hand.
//
// Flash regions the firmware binds its asset views to at boot. Addresses are XIP
// (0x10000000 + partition offset). Forming a pointer from an integer is not a
// constant expression, so the regions are integers and the spans are made at
// runtime (src/target/flash/asset_image.hpp, TableView).

#pragma once

#include <cstddef>
#include <cstdint>

namespace hp2::flash {

struct FlashRegion {
  std::uintptr_t address;
  std::size_t size;
};

// firmware: flash 0x0 .. 0x100000
inline constexpr FlashRegion kFirmware{
    .address = 0x10000000,
    .size = 0x100000,
};

// assets: flash 0x100000 .. 0x800000
inline constexpr FlashRegion kAssets{
    .address = 0x10100000,
    .size = 0x700000,
};

}  // namespace hp2::flash
