#pragma once

#include <cstdint>
#include <utility>

#include <SFML/Window/Keyboard.hpp>

#include "core/key_map.hpp"

namespace hp2::host {

// Neutral keys to SFML scancodes: physical positions, layout independent, which is what the
// original's keyboard interrupt saw (KeyboardHandler, 1:0dcc, stores raw key codes).
constexpr std::int32_t Code(sf::Keyboard::Scancode scancode) {
  return std::to_underlying(scancode);
}

inline constexpr KeyMap kSfmlKeys{{{
    {Key::kNone, Code(sf::Keyboard::Scan::Unknown)},
    {Key::kA, Code(sf::Keyboard::Scan::A)},
    {Key::kB, Code(sf::Keyboard::Scan::B)},
    {Key::kC, Code(sf::Keyboard::Scan::C)},
    {Key::kD, Code(sf::Keyboard::Scan::D)},
    {Key::kE, Code(sf::Keyboard::Scan::E)},
    {Key::kF, Code(sf::Keyboard::Scan::F)},
    {Key::kG, Code(sf::Keyboard::Scan::G)},
    {Key::kH, Code(sf::Keyboard::Scan::H)},
    {Key::kI, Code(sf::Keyboard::Scan::I)},
    {Key::kJ, Code(sf::Keyboard::Scan::J)},
    {Key::kK, Code(sf::Keyboard::Scan::K)},
    {Key::kL, Code(sf::Keyboard::Scan::L)},
    {Key::kM, Code(sf::Keyboard::Scan::M)},
    {Key::kN, Code(sf::Keyboard::Scan::N)},
    {Key::kO, Code(sf::Keyboard::Scan::O)},
    {Key::kP, Code(sf::Keyboard::Scan::P)},
    {Key::kQ, Code(sf::Keyboard::Scan::Q)},
    {Key::kR, Code(sf::Keyboard::Scan::R)},
    {Key::kS, Code(sf::Keyboard::Scan::S)},
    {Key::kT, Code(sf::Keyboard::Scan::T)},
    {Key::kU, Code(sf::Keyboard::Scan::U)},
    {Key::kV, Code(sf::Keyboard::Scan::V)},
    {Key::kW, Code(sf::Keyboard::Scan::W)},
    {Key::kX, Code(sf::Keyboard::Scan::X)},
    {Key::kY, Code(sf::Keyboard::Scan::Y)},
    {Key::kZ, Code(sf::Keyboard::Scan::Z)},
    {Key::kDigit0, Code(sf::Keyboard::Scan::Num0)},
    {Key::kDigit1, Code(sf::Keyboard::Scan::Num1)},
    {Key::kDigit2, Code(sf::Keyboard::Scan::Num2)},
    {Key::kDigit3, Code(sf::Keyboard::Scan::Num3)},
    {Key::kDigit4, Code(sf::Keyboard::Scan::Num4)},
    {Key::kDigit5, Code(sf::Keyboard::Scan::Num5)},
    {Key::kDigit6, Code(sf::Keyboard::Scan::Num6)},
    {Key::kDigit7, Code(sf::Keyboard::Scan::Num7)},
    {Key::kDigit8, Code(sf::Keyboard::Scan::Num8)},
    {Key::kDigit9, Code(sf::Keyboard::Scan::Num9)},
    {Key::kF1, Code(sf::Keyboard::Scan::F1)},
    {Key::kF2, Code(sf::Keyboard::Scan::F2)},
    {Key::kF3, Code(sf::Keyboard::Scan::F3)},
    {Key::kF4, Code(sf::Keyboard::Scan::F4)},
    {Key::kF5, Code(sf::Keyboard::Scan::F5)},
    {Key::kF6, Code(sf::Keyboard::Scan::F6)},
    {Key::kF7, Code(sf::Keyboard::Scan::F7)},
    {Key::kF8, Code(sf::Keyboard::Scan::F8)},
    {Key::kF9, Code(sf::Keyboard::Scan::F9)},
    {Key::kF10, Code(sf::Keyboard::Scan::F10)},
    {Key::kF11, Code(sf::Keyboard::Scan::F11)},
    {Key::kF12, Code(sf::Keyboard::Scan::F12)},
    {Key::kSpace, Code(sf::Keyboard::Scan::Space)},
    {Key::kEscape, Code(sf::Keyboard::Scan::Escape)},
    {Key::kEnter, Code(sf::Keyboard::Scan::Enter)},
    {Key::kTab, Code(sf::Keyboard::Scan::Tab)},
    {Key::kBackspace, Code(sf::Keyboard::Scan::Backspace)},
    {Key::kUp, Code(sf::Keyboard::Scan::Up)},
    {Key::kDown, Code(sf::Keyboard::Scan::Down)},
    {Key::kLeft, Code(sf::Keyboard::Scan::Left)},
    {Key::kRight, Code(sf::Keyboard::Scan::Right)},
    {Key::kInsert, Code(sf::Keyboard::Scan::Insert)},
    {Key::kDelete, Code(sf::Keyboard::Scan::Delete)},
    {Key::kHome, Code(sf::Keyboard::Scan::Home)},
    {Key::kEnd, Code(sf::Keyboard::Scan::End)},
    {Key::kPageUp, Code(sf::Keyboard::Scan::PageUp)},
    {Key::kPageDown, Code(sf::Keyboard::Scan::PageDown)},
    {Key::kLeftShift, Code(sf::Keyboard::Scan::LShift)},
    {Key::kRightShift, Code(sf::Keyboard::Scan::RShift)},
    {Key::kLeftControl, Code(sf::Keyboard::Scan::LControl)},
    {Key::kRightControl, Code(sf::Keyboard::Scan::RControl)},
    {Key::kLeftAlt, Code(sf::Keyboard::Scan::LAlt)},
    {Key::kRightAlt, Code(sf::Keyboard::Scan::RAlt)},
    {Key::kLeftSuper, Code(sf::Keyboard::Scan::LSystem)},
    {Key::kRightSuper, Code(sf::Keyboard::Scan::RSystem)},
    {Key::kMenu, Code(sf::Keyboard::Scan::Menu)},
    {Key::kApostrophe, Code(sf::Keyboard::Scan::Apostrophe)},
    {Key::kComma, Code(sf::Keyboard::Scan::Comma)},
    {Key::kMinus, Code(sf::Keyboard::Scan::Hyphen)},
    {Key::kPeriod, Code(sf::Keyboard::Scan::Period)},
    {Key::kSlash, Code(sf::Keyboard::Scan::Slash)},
    {Key::kSemicolon, Code(sf::Keyboard::Scan::Semicolon)},
    {Key::kEqual, Code(sf::Keyboard::Scan::Equal)},
    {Key::kLeftBracket, Code(sf::Keyboard::Scan::LBracket)},
    {Key::kRightBracket, Code(sf::Keyboard::Scan::RBracket)},
    {Key::kBackslash, Code(sf::Keyboard::Scan::Backslash)},
    {Key::kGrave, Code(sf::Keyboard::Scan::Grave)},
    {Key::kCapsLock, Code(sf::Keyboard::Scan::CapsLock)},
    {Key::kScrollLock, Code(sf::Keyboard::Scan::ScrollLock)},
    {Key::kNumLock, Code(sf::Keyboard::Scan::NumLock)},
    {Key::kPrintScreen, Code(sf::Keyboard::Scan::PrintScreen)},
    {Key::kPause, Code(sf::Keyboard::Scan::Pause)},
    {Key::kKeypad0, Code(sf::Keyboard::Scan::Numpad0)},
    {Key::kKeypad1, Code(sf::Keyboard::Scan::Numpad1)},
    {Key::kKeypad2, Code(sf::Keyboard::Scan::Numpad2)},
    {Key::kKeypad3, Code(sf::Keyboard::Scan::Numpad3)},
    {Key::kKeypad4, Code(sf::Keyboard::Scan::Numpad4)},
    {Key::kKeypad5, Code(sf::Keyboard::Scan::Numpad5)},
    {Key::kKeypad6, Code(sf::Keyboard::Scan::Numpad6)},
    {Key::kKeypad7, Code(sf::Keyboard::Scan::Numpad7)},
    {Key::kKeypad8, Code(sf::Keyboard::Scan::Numpad8)},
    {Key::kKeypad9, Code(sf::Keyboard::Scan::Numpad9)},
    {Key::kKeypadDecimal, Code(sf::Keyboard::Scan::NumpadDecimal)},
    {Key::kKeypadDivide, Code(sf::Keyboard::Scan::NumpadDivide)},
    {Key::kKeypadMultiply, Code(sf::Keyboard::Scan::NumpadMultiply)},
    {Key::kKeypadSubtract, Code(sf::Keyboard::Scan::NumpadMinus)},
    {Key::kKeypadAdd, Code(sf::Keyboard::Scan::NumpadPlus)},
    {Key::kKeypadEnter, Code(sf::Keyboard::Scan::NumpadEnter)},
    {Key::kKeypadEqual, Code(sf::Keyboard::Scan::NumpadEqual)},
}}};

}  // namespace hp2::host
