"""Generate flash_partitions.hpp from a board's partitions.json.

    gen_partition_header.py --input src/boards/<board>/partitions.json \\
        --output src/boards/<board>/flash_partitions.hpp

One constexpr FlashRegion per partition: the absolute XIP address and the
partition size. The firmware binds its asset views inside a region at boot,
after checking the image's digest (src/target/flash/asset_check.hpp).
"""

from __future__ import annotations

import argparse
import logging
import sys
from dataclasses import dataclass
from pathlib import Path

from hp2lib.partition_table import Partition, load_partitions

LOGGER: logging.Logger = logging.getLogger("gen_partition_header")

HEADER_TEMPLATE: str = """// AUTO-GENERATED by scripts/gen_partition_header.py from {args.source} -- do not hand-edit.
//
// Flash regions the firmware binds its asset views to at boot. Addresses are XIP
// (0x10000000 + partition offset). Forming a pointer from an integer is not a
// constant expression, so the regions are integers and the spans are made at
// runtime (src/target/flash/asset_image.hpp, TableView).

#pragma once

#include <cstddef>
#include <cstdint>

namespace hp2::flash {{

struct FlashRegion {{
  std::uintptr_t address;
  std::size_t size;
}};

{args.entries}
}}  // namespace hp2::flash
"""

ENTRY_TEMPLATE: str = """// {args.name}: flash {args.offset:#x} .. {args.end:#x}
inline constexpr FlashRegion k{args.identifier}{{
    .address = {args.address:#010x},
    .size = {args.size:#x},
}};
"""


@dataclass(frozen=True)
class EntryArgs:
    name: str
    offset: int
    end: int
    address: int
    size: int

    @property
    def identifier(self) -> str:
        return "".join(piece.capitalize() for piece in self.name.split("_"))

    @staticmethod
    def from_partition(partition: Partition) -> EntryArgs:
        return EntryArgs(
            name=partition.name,
            offset=partition.offset,
            end=partition.end,
            address=partition.address,
            size=partition.size,
        )


@dataclass(frozen=True)
class HeaderArgs:
    source: str
    entries: str


def render(source: Path) -> str:
    partitions: list[Partition] = load_partitions(source)
    entries: str = "\n".join(
        ENTRY_TEMPLATE.format(args=EntryArgs.from_partition(partition)) for partition in partitions
    )
    return HEADER_TEMPLATE.format(args=HeaderArgs(source=source.name, entries=entries))


def main(argv: list[str]) -> int:
    parser: argparse.ArgumentParser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--input", type=Path, required=True, help="partitions.json")
    parser.add_argument("--output", type=Path, required=True, help="header to write")
    args: argparse.Namespace = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    args.output.write_text(render(args.input))
    LOGGER.info("wrote %s", args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
